spring:
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:inditex
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

server:
  port: 8081
