DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
ID INT NOT NULL,
BRAND_ID VARCHAR(50) NOT NULL,
START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID VARCHAR(50) NOT NULL,
PRIORITY INT NOT NULL,
PRICE DOUBLE PRECISION NOT NULL,
CURR VARCHAR(3) NOT NULL,
PRIMARY KEY (ID)
);